:Author: karstengoo
:Email: {AuthorEmail}
:Date: 27/10/2023
:Revision: version#
:License: Public Domain

= Project: {Project}

Describe your project

== Step 1: Installation
Please describe the steps to install this project.

For example:

1. Open this file
2. Edit as you like
3. Release to the World!

== Step 2: Assemble the circuit

Assemble the circuit following the diagram layout.png attached to the sketch

== Step 3: Load the code

Upload the code contained in this sketch on to your board

=== Folder structure

....
 sketch123                => Arduino sketch folder
  ├── sketch123.ino       => main Arduino file
  ├── schematics.png      => (optional) an image of the required schematics
  ├── layout.png          => (optional) an image of the layout
  └── ReadMe.adoc         => this file
....

=== License
This project is released under a {License} License.

=== Contributing
To contribute to this project please contact karstengoo https://id.arduino.cc/karstengoo

=== BOM
Add the bill of the materials you need for this project.

|===
| ID | Part name      | Part number | Quantity
| R1 | 10k Resistor   | N/A   | 2
| L1 | LED            | N/A   | 1
| E1 | DFRobot FireBeetle ESP32  |  N/A  | 1
| B1 | 3.7V Lipo Bat  |  N/A  | 1
| C1 | Conductive thread  |  N/A  | 1
| R2 | 220 Resistor |  N/A  | 1
| P1| JST XH Bat plug female  |  N/A  | 1
|===
